### ISSUE TITLE
link of "transethnic_prs" doesn't exist.

### ISSUE THREAD

**Issue by RuochengDong** [liangyy/SPrediXcan2PTRS#1]
Hi Dr.Liang,

I was trying to use your software to get the weights for PTRS. However, the link of "transethnic_prs" doesn't exist. Would you mind sending me one? Thank you.

Best regards,
Ruocheng

**Comment by liangyy** [comment]
Hi Ruocheng, thanks for reporting this. Could you try again now?

**Comment by RuochengDong** [comment]
> 

Thank you. It worked.
